development:
  adapter: postgresql
  database: homerun_dev
  host: localhost
  username: maxjacobson
  password: bearvsshark
test:
  adapter: postgresql
  database: homerun_test
  host: localhost
  username: maxjacobson
  password: bearvsshark
production:
  adapter: postgresql
  database: homerun_prod
  host: localhost
